version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: moments-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: moments-backend
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/backups:/app/backups
    env_file:
      - .env  # Ce fichier contient APP_ENV=dev (ou prod)
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: moments-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  pgdata:
