version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: moments-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: moments-backend
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: moments-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata:
