export enum ModalActionType {
  VISIBILITY = 'VISIBILITY',
  DUPLICATE = 'DUPLICATE',
  CANCEL = 'CANCEL',
  DELETE = 'DELETE',
  DELETE_IDEA = 'DELETE_IDEA',
  RESERVER = 'RESERVER',
  PRENDRE = 'PRENDRE',
  ANNULER_RESERVATION = 'ANNULER_RESERVATION',
  RETIRER = 'RETIRER',
  PARTAGE = 'PARTAGE',
  BACK_TO_LIST = 'BACK_TO_LIST',
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC'

}
