"""Ajout des comptes créés avec mail et mdp

Revision ID: 1a0970b2d2d0
Revises: 325435aa1999
Create Date: 2025-07-19 16:36:07.445340

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a0970b2d2d0'
down_revision: Union[str, None] = '325435aa1999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('password', sa.String(length=255), nullable=True))
    op.alter_column('utilisateur', 'nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('utilisateur', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_utilisateur_email', table_name='utilisateur')
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.create_index('ix_utilisateur_email', 'utilisateur', ['email'], unique=False)
    op.alter_column('utilisateur', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('utilisateur', 'nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('utilisateur', 'password')
    # ### end Alembic commands ###
