"""Ajout des comptes tiers

Revision ID: 3af853af78f5
Revises: 9a356adfaadf
Create Date: 2025-07-23 21:28:45.643099

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3af853af78f5'
down_revision: Union[str, None] = '9a356adfaadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('is_compte_tiers', sa.Boolean(), nullable=True))
    op.add_column('utilisateur', sa.Column('gere_par', sa.Integer(), nullable=True))
    op.alter_column('utilisateur', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'utilisateur', 'utilisateur', ['gere_par'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilisateur', type_='foreignkey')
    op.alter_column('utilisateur', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('utilisateur', 'gere_par')
    op.drop_column('utilisateur', 'is_compte_tiers')
    # ### end Alembic commands ###
