"""Ajout  de la date d'expiration de la reservation

Revision ID: 3c4f13691376
Revises: 710ede96e084
Create Date: 2025-06-28 13:20:08.396867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4f13691376'
down_revision: Union[str, None] = '710ede96e084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cadeaux', sa.Column('expiration_reservation', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cadeaux', 'expiration_reservation')
    # ### end Alembic commands ###
