"""Aréation de Gift

Revision ID: 4e1d6f5b4a12
Revises: abedf264a217
Create Date: 2025-05-19 20:40:22.204489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1d6f5b4a12'
down_revision: Union[str, None] = 'abedf264a217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadeau',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commentaire', sa.String(), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('DISPONIBLE', 'RESERVE', 'PRIS', name='giftstatusenum'), nullable=False),
    sa.Column('reserve_par_id', sa.Integer(), nullable=True),
    sa.Column('dateReservation', sa.Date(), nullable=True),
    sa.Column('lieuLivraison', sa.String(), nullable=True),
    sa.Column('dateLivraison', sa.Date(), nullable=True),
    sa.Column('recu', sa.Boolean(), nullable=True),
    sa.Column('marque', sa.String(), nullable=True),
    sa.Column('magasin', sa.String(), nullable=True),
    sa.Column('prixReel', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fraisPort', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('groupe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupe.id'], ),
    sa.ForeignKeyConstraint(['reserve_par_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cadeau_id'), 'cadeau', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cadeau_id'), table_name='cadeau')
    op.drop_table('cadeau')
    # ### end Alembic commands ###
