"""ACéation table cadeaux-partages

Revision ID: 55b11abac33e
Revises: da849a323d4a
Create Date: 2025-05-22 13:19:06.078019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b11abac33e'
down_revision: Union[str, None] = 'da849a323d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadeaux_partages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preneur_id', sa.Integer(), nullable=False),
    sa.Column('cadeau_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rembourse', sa.Boolean(), nullable=True),
    sa.CheckConstraint('participant_id != preneur_id', name='check_pas_soi_meme'),
    sa.ForeignKeyConstraint(['cadeau_id'], ['cadeau.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['preneur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cadeau_id', 'participant_id', name='uix_cadeau_participant')
    )
    op.create_index('ix_cadeaux_partages_cadeau_id', 'cadeaux_partages', ['cadeau_id'], unique=False)
    op.create_index(op.f('ix_cadeaux_partages_id'), 'cadeaux_partages', ['id'], unique=False)
    op.create_index('ix_cadeaux_partages_participant_id', 'cadeaux_partages', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cadeaux_partages_participant_id', table_name='cadeaux_partages')
    op.drop_index(op.f('ix_cadeaux_partages_id'), table_name='cadeaux_partages')
    op.drop_index('ix_cadeaux_partages_cadeau_id', table_name='cadeaux_partages')
    op.drop_table('cadeaux_partages')
    # ### end Alembic commands ###
