"""Ajout des comptes tiers avec is_compte_tiers non nullable

Revision ID: 5a7b035cfe9f
Revises: 3af853af78f5
Create Date: 2025-07-23 21:32:33.051344

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a7b035cfe9f'
down_revision: Union[str, None] = '3af853af78f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateur', 'is_compte_tiers',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateur', 'is_compte_tiers',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
