"""Add token, expiration and utilise fields to invitations

Revision ID: 5f0529a2d56b
Revises: 91467592d137
Create Date: 2025-09-16 19:49:59.216252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0529a2d56b'
down_revision: Union[str, None] = '91467592d137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with temporary defaults for existing data
    op.add_column('invitation', sa.Column('token', sa.String(length=255), nullable=True))
    op.add_column('invitation', sa.Column('date_expiration', sa.DateTime(), nullable=True))
    op.add_column('invitation', sa.Column('utilise', sa.Boolean(), nullable=False, server_default='false'))

    # Generate unique tokens for existing invitations
    op.execute("""
        UPDATE invitation
        SET token = 'legacy_' || id || '_' || extract(epoch from date_envoi)::text
        WHERE token IS NULL
    """)

    # Now make token non-nullable and add unique constraint
    op.alter_column('invitation', 'token', nullable=False)
    op.create_index(op.f('ix_invitation_token'), 'invitation', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_token'), table_name='invitation')
    op.drop_column('invitation', 'utilise')
    op.drop_column('invitation', 'date_expiration')
    op.drop_column('invitation', 'token')
    # ### end Alembic commands ###
