"""remove obsolete code and date_refresh_code columns from group

Revision ID: 8f17f8398062
Revises: 5f0529a2d56b
Create Date: 2025-09-17 20:53:38.789784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f17f8398062'
down_revision: Union[str, None] = '5f0529a2d56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groupe_code_key', 'groupe', type_='unique')
    op.drop_column('groupe', 'date_refresh_code')
    op.drop_column('groupe', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupe', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('groupe', sa.Column('date_refresh_code', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint('groupe_code_key', 'groupe', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
