"""Ajout tentatives-connexion

Revision ID: 9a356adfaadf
Revises: 1a0970b2d2d0
Create Date: 2025-07-19 18:32:31.614902

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a356adfaadf'
down_revision: Union[str, None] = '1a0970b2d2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentatives_connexions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tentatives', sa.Integer(), nullable=False),
    sa.Column('derniere_tentative', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tentatives_connexions_email'), 'tentatives_connexions', ['email'], unique=False)
    op.create_index(op.f('ix_traces_id'), 'traces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traces_id'), table_name='traces')
    op.drop_index(op.f('ix_tentatives_connexions_email'), table_name='tentatives_connexions')
    op.drop_table('tentatives_connexions')
    # ### end Alembic commands ###
