"""Ajout index

Revision ID: bd13892a05a6
Revises: e5edb6d20685
Create Date: 2025-06-13 22:47:55.098765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd13892a05a6'
down_revision: Union[str, None] = 'e5edb6d20685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_gift_reserve_par', 'cadeaux', ['reserve_par_id'], unique=False)
    op.create_index('ix_gift_statut', 'cadeaux', ['statut'], unique=False)
    op.create_index('ix_gift_utilisateur', 'cadeaux', ['destinataire_id'], unique=False)
    op.create_index(op.f('ix_gift_delivery_gift_id'), 'gift_delivery', ['gift_id'], unique=False)
    op.create_index('ix_gift_ideas_propose', 'idees_cadeaux', ['proposee_par_id'], unique=False)
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=False)
    op.create_index('ix_user_group_groupe', 'utilisateur_groupe', ['groupe_id'], unique=False)
    op.create_index('ix_user_group_user', 'utilisateur_groupe', ['utilisateur_id'], unique=False)
    op.create_index('ix_user_group_user_groupe', 'utilisateur_groupe', ['utilisateur_id', 'groupe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_group_user_groupe', table_name='utilisateur_groupe')
    op.drop_index('ix_user_group_user', table_name='utilisateur_groupe')
    op.drop_index('ix_user_group_groupe', table_name='utilisateur_groupe')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_index('ix_gift_ideas_propose', table_name='idees_cadeaux')
    op.drop_index(op.f('ix_gift_delivery_gift_id'), table_name='gift_delivery')
    op.drop_index('ix_gift_utilisateur', table_name='cadeaux')
    op.drop_index('ix_gift_statut', table_name='cadeaux')
    op.drop_index('ix_gift_reserve_par', table_name='cadeaux')
    # ### end Alembic commands ###
