"""description groupe nullable

Revision ID: bfe195328c7c
Revises: 39cc9bd4a905
Create Date: 2025-06-01 14:24:20.782690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe195328c7c'
down_revision: Union[str, None] = '39cc9bd4a905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groupe', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groupe', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
