"""modification date to dateTime

Revision ID: da849a323d4a
Revises: 4e1d6f5b4a12
Create Date: 2025-05-20 22:16:53.708438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da849a323d4a'
down_revision: Union[str, None] = '4e1d6f5b4a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cadeau", schema=None) as batch_op:
        batch_op.alter_column(
            "dateReservation",
            existing_type=sa.Date(),
            type_=sa.DateTime(),
            existing_nullable=True
        )
        batch_op.alter_column(
            "dateLivraison",
            existing_type=sa.Date(),
            type_=sa.DateTime(),
            existing_nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cadeau", schema=None) as batch_op:
        batch_op.alter_column(
            "dateReservation",
            existing_type=sa.DateTime(),
            type_=sa.Date(),
            existing_nullable=True
        )
        batch_op.alter_column(
            "dateLivraison",
            existing_type=sa.DateTime(),
            type_=sa.Date(),
            existing_nullable=True
        )
    # ### end Alembic commands ###
