"""Distinction prenom et nom dans le User , ajout d'une date de création et d'un surnom dans le UserGroup - etape 2

Revision ID: e5edb6d20685
Revises: b17e9b62b6ca
Create Date: 2025-06-13 16:27:57.554310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5edb6d20685'
down_revision: Union[str, None] = 'b17e9b62b6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateur', 'prenom',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('utilisateur', 'nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('utilisateur', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('utilisateur', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('utilisateur', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('utilisateur', 'nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('utilisateur', 'prenom',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
