name: Deploy to Scaleway

on:
  push:
    branches:
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image Backend
        run: |
          docker build -t moments-backend ./backend

      - name: Build image Frontend
        run: |
          docker build -t moments-frontend ./frontend
