CADEAU_DISPONIBLE = "Ce cadeau est disponible et peut être réservé ou pris."
CADEAU_NON_DISPONIBLE = "Le cadeau n'est pas disponible."
CADEAU_INEXISTANT = "Cadeau introuvable."
RESERVATION_VALIDEE = "Vous avez réservé ce cadeau."
CADEAU_NON_RESERVE = "Ce cadeau n'est pas réservé."
CADEAU_NON_PRIS = "Ce cadeau ne peut pas être retiré."
CADEAU_RESERVATION_ANNULEE = "La réservation de ce cadeau a été annulée."
CADEAU_RETIRE = "Le cadeau a été retiré."